server:
    port: 8764

eureka:
    instance:
        hostname: 127.0.0.1
        # 心跳检测检测与续约时间
        lease-renewal-interval-in-seconds: 3   # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
        lease-expiration-duration-in-seconds: 5 #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    client:
        # 注册中心地址
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/

spring:
    application:
        name: integral-server
    # 数据库配置
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/bank_integral?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver # 使用最新的驱动，需要在url中添加serverTimezone
        type: com.alibaba.druid.pool.DruidDataSource

# mybatis配置
mybatis:
    # xml所在的位置
    mapper-locations: classpath:mappings/*/*/*.xml
    # entity扫描的包名
    type-aliases-package: com.shanghai.bank.modules.*
    configuration:
        # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
        cache-enabled: true
        # 缓存一个会话中执行的所有查询
        local-cache-scope: session
        # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载， 这里需要false 不然api 接口collection 加载不了
        lazy-loading-enabled: false
        # 有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载
        aggressive-lazy-loading: false
        # 是否允许单条sql 返回多个数据集  (取决于驱动的兼容性) default:true
        multiple-result-sets-enabled: true
        # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
        use-column-label: true
        # 允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，有一些驱动器不兼容不过仍然可以执行。  default:false
        use-generated-keys: false
        # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射　PARTIAL:部分  FULL:全部
        auto-mapping-behavior: partial
        # 默认的执行类型  （SIMPLE: 简单； REUSE: 执行器可能重复使用prepared statements语句；BATCH: 执行器可以重复执行语句和批量更新）
        default-executor-type: simple
        # 解决，查询返回结果含null没有对应字段值问题
        call-setters-on-nulls: true
        # 设置超时时间，它决定驱动等待数据库响应的秒数。
        default-statement-timeout: 25
        # 为驱动的结果集获取数量（fetchSize）设置一个提示值。此参数只可以在查询设置中被覆盖。
        default-fetch-size: 100
        # 允许在嵌套语句中使用分页（RowBounds）。如果允许使用则设置为false。
        safe-row-bounds-enabled: false
        # 使用驼峰命名法转换字段
        map-underscore-to-camel-case: true
        # 默认为OTHER,为了解决oracle插入null报错的问题要设置为NULL
        jdbc-type-for-null: null
        # 指定哪个对象的方法触发一次延迟加载
        lazy-load-trigger-methods: [equals,clone,hashCode,toString]
        # 指定 MyBatis 所用日志的具体实现
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
