server:
    port: 8661

spring:
    application:
        name: pay-eureka

eureka:
    instance:
        hostname: 127.0.0.1
    client:
        # 防止注册中心自我注册
        register-with-eureka: false
        #如果为true，启动时报警.
        fetch-registry: false
        service-url:
            defaultZone: http://127.0.0.1:8661/eureka/